name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set Node Version
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.1
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install monorepo deps
      run: yarn
    - name: Install package deps
      run: yarn lerna bootstrap
    - name: Run Tests
      run: yarn lerna run test

  publish:
    # needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: 'master'
    - name: Checkout master
      run: git checkout master
    - name: Set Node Version
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.1
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install monorepo deps
      run: yarn
    - name: Git status
      run: git status
    - name: Install package deps
      run: yarn lerna exec yarn --parallel -- --frozen-lockfile
    - name: Git status
      run: git status
    - name: Setup .npmrc
      run: echo "//registry.npmjs.org/:_authToken={{ secrets.NPM_TOKEN }}" > .npmrc
    - name: Setup git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Publish
      env:
        GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
      run: yarn lerna publish from-git --conventional-commits --yes --git-remote https://$GITHUB_SECRET@github.com/hstove/bsk-analytics
